homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation:  !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Brussels
  temperature_unit: C
  customize: !include customize.yaml
  

# Enables the frontend
frontend:

http:
  api_password: !secret password
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

# camera:
#   - platform: mjpeg
#     mjpeg_url: http://192.168.0.192:8081
#     name: Webcam

# camera:
#     - platform: generic
#       still_image_url: http://api.sat24.com/animated/EU/visual/1/Central%20European%20Standard%20Time/9561397
#       name: Europe

mqtt:
    broker: 0.0.0.0
    port: 1883
    client_id: home-assistant-1
    keepalive: 60
    username: !secret mqtt_username
    password: !secret mqtt_password

config:

device_tracker: !include includes/device_trackers.yaml
media_player: !include includes/media_players.yaml
zone: !include_dir_merge_list includes/zones
sensor: !include_dir_list  includes/sensor
light: !include_dir_list includes/lights
group: !include_dir_named includes/groups
scene: !include_dir_list includes/scenes
automation: !include_dir_list includes/automation
camera: !include_dir_list includes/cameras
script: !include_dir_named scripts/

logger:
  default: warning
  logs:
    homeassistant.components.device_tracker.mqtt: debug