homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation:  !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Brussels
  temperature_unit: C

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.0.192:8081
    name: Webcam

mqtt:
    broker: 192.168.0.192
    port: 1883
    client_id: home-assistant-1
    keepalive: 60
    username: !secret mqtt_username
    password: !secret mqtt_password

sensor: !include_dir_merge_list includes/sensors
light: !include_dir_merge_list includes/light
script: !include_dir_merge_named scripts/

# Example configuration.yaml automation entry
automation:
- alias: Known person in front of my door
  trigger:
    platform: event
    event_type: identify_face
    event_data:
      entity_id: image_processing.microsoftface_webcam
      name: 'Glenn'
  action:
    service: script.welcoming

# Example configuration.yaml entry
logger:
  default: warning
  logs:
    homeassistant.components.device_tracker.mqtt: debug

microsoft_face:
  api_key: !secret microsoft_face_key

image_processing:
 - platform: microsoft_face_identify
   group: family
   source:
    - entity_id: camera.webcam