alias: "Chromecast started"
trigger:
    - platform: state
      entity_id: media_player.glennchromecast
      from: 'idle'
      to: 'playing'
action:
    - service: scene.turn_on
      entity_id: scene.room_glenn_off