- platform: owntracks
  max_gps_accuracy: 200

# - platform: ddwrt
#   host: 192.168.0.3
#   username: !secret ddwrt_user
#   password: !secret ddwrt_password

# - platform: bluetooth_tracker    

  # - platform: gpslogger


#  - platform: netgear
#    host: 192.168.0.2
#    username: admin
#    password: password
